using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IvyCore.Parametric
{
    /// <summary>
    /// Tuple interface as an abstract base class.
    /// </summary>
    public abstract class ITuple : ICloneable, IComparable<ITuple>
    {
        protected int[] tuple;

        /// <summary>
        /// Tuple dimension.
        /// </summary>
        public int Dim
        {
            get { return tuple.Length; }
        }
        public int this[int i]
        {
            get
            {
                return tuple[i];
            }
            set
            {
                this.tuple[i] = value; 
            }
        }

        protected ITuple(IList<int> tuple)
        {
            this.tuple = tuple.ToArray<int>();
        }

        /// <summary>
        /// For a given indexRange, compute the contiguous index of this tuple.
        /// </summary>
        /// <param name="dimCount">
        /// An array that holds for each dimension the number of indices.
        /// For instance, if a tuple represents a node adress belonging to a grid generated by [[0,1],[-5,10,3]],
        /// dimCount will be [2,3]. It it represents a cell adress then dimCount will be [1,2].
        /// </param>
        /// <returns>The contiguous index.</returns>
        protected int IndexFromTuple(IList<int> dimCount)
        {
            int index = this.tuple[0];
            int nprod = 1;
            for (int i = 0; i < this.tuple.Length - 1; i++)
            {
                nprod *= dimCount[i];
                index += nprod * tuple[i + 1];
            }
            return index;
        }

        /// <summary>
        /// Get a tuple from its contiguous index.
        /// </summary>
        /// <param name="index">The index to convert.</param>
        /// <param name = "dimCount">
        /// An array that holds for each dimension the number of indices.
        /// For instance, if a tuple represents a node adress belonging to a grid generated by [[0,1],[-5,10,3]],
        /// dimCount will be [2,3]. It it represents a cell adress then dimCount will be [1,2].
        /// </param>
        /// <returns>The tuple corresponding to the given index.</returns>
        protected static IList<int> TupleFromIndex(int index, IList<int> dimCount)
        {
            int n = dimCount.Count;
            var tuple = new int[n];

            int q = index;
            int r;
            for (int i = 0; i < n - 1; i++)
            {
                q = Math.DivRem(q, dimCount[i], out r);
                tuple[i] = r;
            }
            tuple[n - 1] = q;
            return tuple;
        }

        /// <summary>
        /// String representation of a tuple.
        /// </summary>
        /// <param name="tuple">The tuple.</param>
        /// <returns>A string representing the tuple (i0,i1,...,in-1).</returns>
        public override string ToString()
        {
            var s = "(" + this.tuple[0];
            for (int i = 1; i < this.tuple.Length; i++)
            {
                s += ", " + tuple[i];
            }
            return s += ")";
        }
        public int CompareTo(ITuple tuple)
        {
            int dim = tuple.Dim;
            if (dim != this.Dim)
            {
                throw new System.ArgumentOutOfRangeException("The tuples must be of same dimension to be comparable");
            }
            // Backward Loop
            for (int d = dim; d > 0; d--)
            {
                int i1 = this[d];
                int i2 = tuple[d];

                if (i2 > i1)
                {
                    // this < tuple
                    return -1;
                }
                else if (i2 < i1)
                {
                    // this > tuple
                    return 1;
                }
            }
            // tuples are equals
            return 0;
        }
        public abstract object Clone();
    }


}
